This is makeindex, version 2.17 [TeX Live 2023] (kpathsea + Thai support).
Scanning style file ./Thesis.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file Thesis.acn....done (24 entries accepted, 0 rejected).
Sorting entries....done (109 comparisons).
Generating output file Thesis.acr....done (46 lines written, 0 warnings).
Output written in Thesis.acr.
Transcript written in Thesis.alg.
