This is makeindex, version 2.17 [TeX Live 2023] (kpathsea + Thai support).
Scanning style file /Users/josu/Desktop/uoc/tfm/bidaia-tex/.texpadtmp/Thesis.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file /Users/josu/Desktop/uoc/tfm/bidaia-tex/.texpadtmp/Thesis.acn....done (3 entries accepted, 0 rejected).
Sorting entries....done (5 comparisons).
Generating output file /Users/josu/Desktop/uoc/tfm/bidaia-tex/.texpadtmp/Thesis.acr....done (12 lines written, 0 warnings).
Output written in /Users/josu/Desktop/uoc/tfm/bidaia-tex/.texpadtmp/Thesis.acr.
Transcript written in /Users/josu/Desktop/uoc/tfm/bidaia-tex/.texpadtmp/Thesis.alg.
